Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\sse\AppData\Local\Programs\Python\Python37-32\generate parenthesis.py 
n=3
()()()
()(())
(())()
(()())
((()))
>>> 
 RESTART: C:\Users\sse\AppData\Local\Programs\Python\Python37-32\generate parenthesis.py 
n=1
()
>>> 
 RESTART: C:\Users\sse\AppData\Local\Programs\Python\Python37-32\generate parenthesis.py 
n=5
()()()()()
()()()(())
()()(())()
()()(()())
()()((()))
()(())()()
()(())(())
()(()())()
()(()()())
()(()(()))
()((()))()
()((())())
()((()()))
()(((())))
(())()()()
(())()(())
(())(())()
(())(()())
(())((()))
(()())()()
(()())(())
(()()())()
(()()()())
(()()(()))
(()(()))()
(()(())())
(()(()()))
(()((())))
((()))()()
((()))(())
((())())()
((())()())
((())(()))
((()()))()
((()())())
((()()()))
((()(())))
(((())))()
(((()))())
(((())()))
(((()())))
((((()))))
>>> 
 RESTART: C:\Users\sse\AppData\Local\Programs\Python\Python37-32\generate parenthesis.py 
n=-1
>>> 
 RESTART: C:\Users\sse\AppData\Local\Programs\Python\Python37-32\generate parenthesis.py 
n=4
()()()()
()()(())
()(())()
()(()())
()((()))
(())()()
(())(())
(()())()
(()()())
(()(()))
((()))()
((())())
((()()))
(((())))
>>> 
